# Generated by Django 4.0.1 on 2022-06-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockalgebraege',
            options={'verbose_name': 'Программа блока Алгебра ЕГЭ', 'verbose_name_plural': 'Программы блоков Алгебра ЕГЭ'},
        ),
        migrations.AlterModelOptions(
            name='blockgeometriaege',
            options={'verbose_name': 'Программа блока Геометрия ЕГЭ', 'verbose_name_plural': 'Программы блоков Геометрия ЕГЭ'},
        ),
        migrations.AlterField(
            model_name='blockalgebraege',
            name='file_algebra_ege',
            field=models.FileField(upload_to='algebra/', verbose_name='Файл блока'),
        ),
        migrations.AlterField(
            model_name='blockalgebraege',
            name='title_algebra_ege',
            field=models.CharField(max_length=255, verbose_name='Название блока'),
        ),
        migrations.AlterField(
            model_name='blockgeometriaege',
            name='file_geometria_ege',
            field=models.FileField(upload_to='geometria/', verbose_name='Файл блока'),
        ),
        migrations.AlterField(
            model_name='blockgeometriaege',
            name='title_geometria_ege',
            field=models.CharField(max_length=255, verbose_name='Название блока'),
        ),
        migrations.AlterField(
            model_name='variantege',
            name='file_ege',
            field=models.FileField(upload_to='ege/', verbose_name='Файл варианта'),
        ),
        migrations.AlterField(
            model_name='variantege',
            name='title_ege',
            field=models.CharField(max_length=255, verbose_name='Номер варианта'),
        ),
    ]
