# Generated by Django 4.0.1 on 2022-06-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_twocoursevideo_alter_onecoursevideo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metodical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ege', models.CharField(max_length=255, verbose_name='Название')),
                ('file_ege', models.FileField(upload_to='metodical/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Методические указания',
                'verbose_name_plural': 'Методические указания',
            },
        ),
    ]
