# Generated by Django 4.0.1 on 2022-06-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_metodical'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodicalTwoCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ege', models.CharField(max_length=255, verbose_name='Название')),
                ('file_ege', models.FileField(upload_to='metodical/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Методические указания 2 курса',
                'verbose_name_plural': 'Методические указания 2 курса',
            },
        ),
        migrations.RenameModel(
            old_name='Metodical',
            new_name='MetodicalOneCourses',
        ),
        migrations.AlterModelOptions(
            name='metodicalonecourses',
            options={'verbose_name': 'Методические указания 1 курса', 'verbose_name_plural': 'Методические указания 1 курса'},
        ),
    ]
