# Generated by Django 4.0.1 on 2022-06-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_metodicaltwocourses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metodicalonecourses',
            old_name='file_ege',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='metodicalonecourses',
            old_name='title_ege',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='metodicaltwocourses',
            old_name='file_ege',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='metodicaltwocourses',
            old_name='title_ege',
            new_name='title',
        ),
    ]
