# Generated by Django 4.0.2 on 2022-06-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='variant_oge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='ege/')),
            ],
            options={
                'verbose_name': 'Вариант ОГЭ',
                'verbose_name_plural': 'Варианты ОГЭ',
            },
        ),
    ]
