# Generated by Django 4.0.1 on 2022-06-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='file_cert',
            field=models.FileField(upload_to='cert/', verbose_name='Файл сертификата'),
        ),
        migrations.AlterField(
            model_name='cert',
            name='title_cert',
            field=models.CharField(max_length=255, verbose_name='Название сертификата'),
        ),
    ]
