# Generated by Django 4.0.2 on 2022-06-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='certificate',
            new_name='cert_main',
        ),
        migrations.AlterModelOptions(
            name='cert_main',
            options={'verbose_name': 'Сертификат', 'verbose_name_plural': 'Сертификаты'},
        ),
    ]
